# Define some common tasks for development
test-release:
	python release_to_github.py --username ${github_username} --password ${github_password} --repo qiuwch/unrealcv --file Makefile

release:
	python release_to_github.py
